// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySqlContext))]
    partial class MySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "Category2",
                            Description = "Description2",
                            ImageURL = "https://www.google.com/2",
                            Name = "Name2",
                            Price = 20m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Category3",
                            Description = "Description3",
                            ImageURL = "https://www.google.com/3",
                            Name = "Name3",
                            Price = 30m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Category4",
                            Description = "Description4",
                            ImageURL = "https://www.google.com/4",
                            Name = "Name4",
                            Price = 40m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Category5",
                            Description = "Description5",
                            ImageURL = "https://www.google.com/5",
                            Name = "Name5",
                            Price = 50m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Category6",
                            Description = "Description6",
                            ImageURL = "https://www.google.com/6",
                            Name = "Name6",
                            Price = 60m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Category7",
                            Description = "Description7",
                            ImageURL = "https://www.google.com/7",
                            Name = "Name7",
                            Price = 70m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Category8",
                            Description = "Description8",
                            ImageURL = "https://www.google.com/8",
                            Name = "Name8",
                            Price = 80m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Category9",
                            Description = "Description9",
                            ImageURL = "https://www.google.com/9",
                            Name = "Name9",
                            Price = 90m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Category10",
                            Description = "Description10",
                            ImageURL = "https://www.google.com/10",
                            Name = "Name10",
                            Price = 100m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "Category11",
                            Description = "Description11",
                            ImageURL = "https://www.google.com/11",
                            Name = "Name11",
                            Price = 110m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryName = "Category12",
                            Description = "Description12",
                            ImageURL = "https://www.google.com/12",
                            Name = "Name12",
                            Price = 120m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryName = "Category13",
                            Description = "Description13",
                            ImageURL = "https://www.google.com/13",
                            Name = "Name13",
                            Price = 130m
                        },
                        new
                        {
                            Id = 14L,
                            CategoryName = "Category14",
                            Description = "Description14",
                            ImageURL = "https://www.google.com/14",
                            Name = "Name14",
                            Price = 140m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
